config/routes.rb
Rails.application.routes.draw do
  get '/forbidden' => 'error#unauthorized'
  get 'referral/index'
  # get 'user/index'
  devise_for :user, controllers: { sessions: 'user/sessions' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # devise_for :users, controllers: { sessions: 'users/sessions' }
  # Defines the root path route ("/")
  root "referral#index"
  get 'user/admin' => 'user#admin'
  get 'user/send_email' => 'user#send_email'
  post 'user/send_mail' => 'user#send_mail'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def validate_user_role!(role)
    redirect_to forbidden_path unless current_user != nil && current_user.has_role?(role)
  end
end

app/controllers/error_controller.rb
class ErrorController < ApplicationController
  def unauthorized
  end
end

app/controllers/referral_controller.rb
class ReferralController < ApplicationController
  before_action :authenticate_user!
  before_action do
    validate_user_role!(:referral)
  end
  def index
      @user = User.all
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
    User.where(email:params[:user][:email]).first&.update!(status:true)
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!

  before_action do
    validate_user_role!(:admin)
  end

  def admin
    @user = User.where(referred_by_id: current_user.id)
  end

  def send_email

  end

  def send_mail
    email = params[:email]
    user_exist = User.find_by(email:email)
    if(user_exist)
      count = user_exist.action_count.present? ? user_exist.action_count+1 : 1
      user_exist.update!(action_count: count)
    else
      u = User.new(email:email, password:email, referred_by_id: current_user.id, action_count:1)
      u.save!
      u.add_role(:referral)
    end
    if(user_exist.action_count < 5)
    UserMailer.with(email: email).welcome_email.deliver_now
      redirect_to '/user/send_email', flash:{success: "sent the email"}
    else
      redirect_to '/user/send_email', flash:{success: "Resent email is sent max times"}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/referral_helper.rb
module ReferralHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DirectShiftTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%#= javascript_include_tag :defaults %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/referral/index.html.erb
<div class="container-fluid">
  <div class="panel panel-default" style="margin-top: 1.5%;">
    <div class="panel-body">
      <h1>Referral User</h1>
      <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
      <table class="table table-striped" style="table-layout: fixed; width: 100%" >
        <thead>
        <tr>
          <th>Index</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th>Referred By</th>
        </tr>
        </thead>

        <tbody>
        <% @user&.each_with_index do |user, index| %>
          <tr>
            <td style="text-align:left !important;"><%= index + 1 %></td>
            <td><%= user&.first_name %></td>
            <td><%=user&.last_name %></td>
            <td><%=user&.email %></td>
            <td><%=user&.referred_by_id %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/user/admin.html.erb
<div class="container-fluid">
  <div class="panel panel-default" style="margin-top: 1.5%;">
    <div class="panel-body">
      <h1>Referral User</h1>
      <%= link_to 'Logout', destroy_user_session_path %>
      <table class="table table-striped" style="table-layout: fixed; width: 100%" >
        <thead>
        <tr>
          <th>Index</th>
          <th>Email</th>
          <th>Status</th>
          <th>Action</th>
        </tr>
        </thead>

        <tbody>
        <% @user&.each_with_index do |user, index| %>
          <tr>
            <td style="text-align:left !important;"><%= index + 1 %></td>
            <td><%=user&.email %></td>
            <td><%=user&.status %></td>
            <td>
            <% if (user&.action_count.present? ? user&.action_count : 0) < 5 %>
             <%= link_to 'Resend Invite', user_send_email_path(email: user&.email)%>
            <% else %>
              Don't Send the Invite
              <% end %>
                </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/user/send_email.html.erb
<div class="container-fluid">
  <div class="panel panel-default" style="margin-top: 1.5%;">
    <div class="panel-body">
      <h1>Send Referral</h1>
      <%= form_with url: '/user/send_mail', method: :post do |f| %>
        <div class="vertical-center">
          <div>
            <%= f.label :label, 'Email:', class: "control-label" %>
            <%= f.text_field :email,  class: 'form-control' %>
          </div>
          <%= f.submit "Send", class: "btn btn-orange mt-2" %>
        </div>
      <% end %>
    </div>
  </div>
</div>